image:
- Visual Studio 2017
- Ubuntu

for:
  - matrix:
      only:
        - image: Visual Studio 2017

    before_build:
      - gitversion /l console /output buildserver

    build_script:
      - ps: .\build.ps1 $env:GitVersion_NuGetVersion
      - ps: .\build.ps1

    test_script:
      - ps: .\test.ps1

    artifacts:
      - path: '*\bin\Release\*.nupkg'

    deploy:
      provider: Environment
      name: NuGet
      on:
        appveyor_repo_tag: true

  - matrix:
      only:
        - image: Ubuntu

    build_script:
      - sh: ./build.sh

    test_script:
      - sh: ./test.sh
